repos:

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
    -   id: pyupgrade
        args: [--exit-zero-even-if-changed]
        exclude_types: [xml]
        language: python

-   repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
    -   id: isort
        args: ["--profile", "black"]
        language: python

-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        exclude: ^tests/
        args: [--line-length=79]
        exclude_types: [xml]
        language: python
    # -   id: black-jupyter
    #     args: [--line-length=79]

-   repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
        language: python

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-builtin-literals
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: check-xml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: forbid-new-submodules
    -   id: trailing-whitespace
    -   id: check-merge-conflict
